[env:seeed_xiao_esp32c6]
platform = espressif32
board = seeed_xiao_esp32c6
framework = espidf
monitor_speed = 115200
board_build.mcu = esp32c6
board_build.src_dir = src
board_build.partitions = partitions.csv
board_upload.flash_size = 4MB
